name: Reusable NPM Deployment Workflow

on:
  workflow_call:
    inputs:
        PR_number:
          description: 'Pull request number'
          required: true
          type: string
        src_path:
          description: 'Source path to deploy'
          required: true
          type: string
        remote_path:
          description: 'Remote path on the server'
          required: true
          type: string
        remote_host:
          description: 'Remote host address'
          required: true
          type: string
        remote_user:
          description: 'Remote user for SSH'
          required: true
          type: string
    secrets:
        SSH_PRIVATE_KEY:
          description: 'SSH private key for remote server'
          required: true
               
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.PR_number }}

      - name: Deploy to staging
        uses: burnett01/rsync-deployments@23a557dceb19f9bb960ef40cf75cab5e9b37ec1f
        with:
          switches: -avzr --delete
          path: ${{ inputs.src_path }}
          remote_path: ${{ inputs.remote_path }}
          remote_host: ${{ inputs.remote_host }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
        with:
          hosts: '${{ inputs.remote_user }}@${{ inputs.remote_host }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ${{ inputs.remote_path }}
            npm ci
            pm2 start /var/app/web/bin/www || pm2 restart /var/app/web/bin/www
            sudo service nginx restart

      - name: Update status
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Staging server created
            > PR #${{ github.event.inputs.PR_number }} has been deployed successfully

            URL: http://${{ inputs.remote_host }}`;

            github.rest.issues.createComment({
              issue_number: ${{ github.event.inputs.PR_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
