name: Continuous Deployment Workflow

# This workflow is triggered whenever commits are pushed to the main branch
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    # Define the working directory for all run steps in the workflow
    working-directory: ./web


jobs:
    deploy_staging:
      environment: staging
      name: 'Deploy to fixed staging'
      runs-on: ubuntu-latest

      steps:
          uses: bLACKZU/npm-ci-cd-actions/.github/workflows/called-deploy.yaml@main
          with:
              PR_number: main
              src_path: ./web
              remote_path: /var/app
              remote_host: ${{ vars.STAGING_HOST }}
              remote_user: ubuntu
          secrets:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    deploy_production:
        environment: production
        name: 'Gated deployment to production'
        runs-on: ubuntu-latest
        needs: deploy_staging

        steps:
            uses: bLACKZU/npm-ci-cd-actions/.github/workflows/called-deploy.yaml@main
            with:
              PR_number: main
              src_path: ./web
              remote_path: /var/app
              remote_host: ${{ vars.PRODUCTION_HOST }}
              remote_user: ubuntu
            secrets:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
